AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - staging
      - production
  Region:
    Type: String
  SGStackName:
    Type: String
  VPCStackName:
    Type: String
  AMIImageId:
    Type: String

Resources:
  EC2InstanceA:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: AMIImageId
      KeyName: MyKeyPair
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue:
              Fn::Join: ["-", [Ref: VPCStackName, "PublicSubnetA"]]
          GroupSet:
            - Fn::ImportValue:
                Fn::Join: ["-", [Ref: SGStackName, ApplicationSecurityGroup]]
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          git clone https://github.com/souhub/fastapi-tutorial
          cd ./fastapi-tutorial
          pip3 install -r ./docker/api/requirements.txt
          cd ./app && uvicorn main:app --reload --port=8000 --host=0.0.0.0

      Tags:
        - Key: Name
          Value:
            Fn::Join: ["-", [Ref: Prefix, Ref: Environment, "EC2InstanceA"]]

Outputs:
  EC2InstanceA:
    Value:
      Ref: EC2InstanceA
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-EC2InstanceA"
