AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - staging
      - production
  VPCStackName:
    Type: String

Resources:
  ApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Application Security Group"
      VpcId:
        Fn::ImportValue:
          Fn::Join: ["-", [Ref: VPCStackName, "VPC"]]
      # HTTP (80), HTTP (8080) のインバウンドを許可
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
          # SourceSecurityGroupId:
          #   Ref: ALBSecurityGroup
        # SSH接続を許可（ec2.ymlでKeyNameの設定の必要あり）

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value:
            Fn::Join: ["-", [Ref: Prefix, Ref: Environment, "application"]]

Outputs:
  ApplicationSecurityGroup:
    Value:
      Ref: ApplicationSecurityGroup
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-ApplicationSecurityGroup"
